version: "3"

services:

  viet_gold:
    # A container that exposes an API to show its IP address
    image: viet_gold
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.viet_gold.rule=Host(`quanly.camdovietgold.com`)"
        - "traefik.http.routers.viet_gold.entrypoints=web"
        - "traefik.http.services.viet_gold.loadbalancer.server.port=5000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
